- hosts: terraform-ansible
  tasks:
    - name: Atualizando pip, setuptools e wheel
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - pip
          - setuptools
          - wheel
        state: latest

    - name: Instalando o Python3 e Virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes   
      
    - name: Git Clone
      ansible.builtin.git:
        repo: https://github.com/alura-cursos/clientes-leo-api.git
        dest: /home/ubuntu/tcc
        version: master
        force: yes

    - name: Instalando Dependencias com pip
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        requirements: /home/ubuntu/tcc/requirements.txt

    - name: Instalando dependências com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework

    - name: Alterando os hosts do settings 
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

    - name: Configurando o banco de dados
      shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py migrate'

    - name: Carregando dados iniciais
      shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py loaddata clientes.json'
    - name: Iniciando o servidor
      shell: '. /home/ubuntu/tcc/venv/bin/activate; nohup python /home/ubuntu/tcc/manage.py runserver 0.0.0.0:8000 &'